### ISSUE TITLE
Remove pixel of whitespace at far right of rating module

### ISSUE THREAD

**Issue by rossjrw** [Nu-SCPTheme/Nu-SCP#12]
![rating](https://usercontent.irccloud-cdn.com/file/dbe70NHM/Screenshot%202019-01-26%20at%2020.55.23.png)

**Comment by Woedenaz** [comment]
This seems to be related to the fact that the rating module does not have a fixed width, for whatever reason. It is remedied by giving the module a width, for whatever reason.

**Comment by rossjrw** [comment]
I'd prefer to avoid giving the rating module a fixed width, if possible
