### ISSUE TITLE
Fix spacing of "+ Options" expandable

### ISSUE THREAD

**Issue by TSATPWTCOTTTADC** [Nu-SCPTheme/Nu-SCP#13]
Clicking "+ Options" in page-options-container causes the resultant popup to mostly overlap with the already visible options.

[Screenshot](https://i.imgur.com/OzCHgEo.png)

Replicated on Windows 7 in Firefox 64 and Internet Explorer 11.

**Comment by Woedenaz** [comment]
This has been fixed by removing the `height: 1%` from `.page-options-bottom`
Should perhaps push to stable as well. This only seems to be an issue with Firefox, for whatever reason.
