### ISSUE TITLE
Mobile sidebar is impossible to close on sigma9+nuSCP

### ISSUE THREAD

**Issue by rossjrw** [Nu-SCPTheme/Nu-SCP#24]

**Comment by Woedenaz** [comment]
This must be related to z-index. I'll take a look.

**Comment by Woedenaz** [comment]
I cannot replicate this issue. I'll need a page or something in order to figure out what is going on.

**Comment by rossjrw** [comment]
http://scptestwiki.wikidot.com/sigma:mzl-1730

Looks like it's only happening on sigma pages on the test wiki. Think #skrollr-body might be broken in the beta release. That's fine, we're not using #skrollr-body on the main wiki

My bad, should've made sure to check different pages.
