### ISSUE TITLE
Topbar cannot be allowed to horizontally overflow

### ISSUE THREAD

**Issue by rossjrw** [Nu-SCPTheme/Nu-SCP#3]
The tabs/links/whatever they are in the grey thing on the header cannot be allowed to overflow onto the next line

Either reformat the grey bit so it can accommodate another row if need be, or just cut excess tabs off

**Comment by Woedenaz** [comment]
This has more or less been fixed with the mobile breakpoint been changed to 768px.
However, if we want to make sure not to let this happen, the simple fix is in header.css:

```css
#top-bar .top-bar > ul {
    flex-wrap: nowrap;
}
```

Changing that should do it.

**Comment by Woedenaz** [comment]
Croque, does this still happen? I haven't been noticing it on the website as of late.

**Comment by Woedenaz** [comment]
This is fixed.
