### ISSUE TITLE
Add fallback values for browsers that don't support CSS variables.

### ISSUE THREAD

**Issue by TSATPWTCOTTTADC** [Nu-SCPTheme/Nu-SCP#31]
For browsers like Internet Explorer most of the the navigation elements are white on a white background:
![iexplore_n0w1ulfqp1](https://user-images.githubusercontent.com/37148714/53293166-ecdf6500-379c-11e9-8c94-da25f9014b3f.png)

Working around IE's lack of CSS variable support might be all that is needed, provided there isn't something other factor messing things up on IE.

**Comment by Woedenaz** [comment]
This has been implemented

**Comment by ammongit** [comment]
@Woedenaz link the PR or commit hash?
