### ISSUE TITLE
Mobile topbar dropdown obscures too much of the page and isn't scrollable

### ISSUE THREAD

**Issue by TSATPWTCOTTTADC** [Nu-SCPTheme/Nu-SCP#33]
Mobile. Sigma9+NuSCP. Browser: Samsung Internet 8.2.
This doesn't appear on http://scptestwiki.wikidot.com/ but this was happening on http://scp-wiki.wikidot.com/ a day or so ago. Can't test it right now on the main site. Will try to next chance I get.
When clicking the `SCPs` button in the topbar there's almost nowhere to click to cancel out of this drop down because everything on the screen is a link to somewhere else. Also, I can't scroll it past SCP-3199. It just stays stuck where it is when I scroll - the page content under it scrolls but the dropdown it stays exactly where it is on my screen.
![tall_screenshot](https://user-images.githubusercontent.com/37148714/53307350-8d995780-3865-11e9-9b81-52917bc87313.jpg)

**Comment by Woedenaz** [comment]
This has been fixed, as far as I am aware.
