### ISSUE TITLE
Mobile "SCPs" dropdown is missing entries

### ISSUE THREAD

**Issue by TSATPWTCOTTTADC** [Nu-SCPTheme/Nu-SCP#34]
Sigma9+NuSCP. 
Mobile. Android 8.0.0. Browser: Samsung Internet 8.2.
Desktop. Windows 7. Browser: Firefox 65.

In the top bar, in the "SCPs" menu the "Heritage Collection" text links to http://www.scp-wiki.net/user-curated-lists, not http://www.scp-wiki.net/heritage-collection-arc as the name would suggest.

The "SCPs" top bar menu is also missing links to each hundredth article in each series and links to Joke SCPs, Archived SCPs, Explained SCPs, Anomalous Items, Extranormal Events, and Unexplained Locations. These links are present in mobile Sigma-9.

![nu](https://user-images.githubusercontent.com/37148714/54091148-ca2f7d80-4352-11e9-9681-b55e451c06cf.jpg)

**Comment by Woedenaz** [comment]
This is fixed

**Comment by TSATPWTCOTTTADC** [comment]
After a recent change to http://www.scp-wiki.net/nav:top this menu is again missing some entries. 

It is now showing only two links - Series I and Series II. 
https://i.imgur.com/h4uapKJ.jpg
