### ISSUE TITLE
Mobile "SCP Series" dropdown is missing entries

### ISSUE THREAD

**Issue by TSATPWTCOTTTADC** [Nu-SCPTheme/Nu-SCP#38]
Similar to https://github.com/Nu-SCPTheme/Nu-SCP/issues/34#issue-419230090

After a recent change to http://www.scp-wiki.net/nav:top this menu is again missing some entries. 

It is now showing only two links - Series I and Series II. 
https://i.imgur.com/h4uapKJ.jpg

**Comment by rossjrw** [comment]
Should be fixed now.
